version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7755:7755"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=core/server.py
    command: bash run.sh